name: Backup GitHub to GitLab

on:
  push:
    branches:
      - main  # main 브랜치 변경 시 동기화
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 히스토리를 가져오도록 설정
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to GitLab Mirror
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/backup6695808/somaz94.git
          git push --prune gitlab refs/remotes/origin/*:refs/heads/* refs/tags/*
        continue-on-error: true
